### ISSUE TITLE
Ensure IP address is from client

### ISSUE THREAD

**Issue by eshtadc** [DevFactoryCH/Mollom#1]
The client code to identify the ip address assumes the $_SERVER['REMOTE_ADDR'] will provide the correct address, but this isn't the case when we get into the land of proxy servers, etc.

You could implement something like the Mollom example app does: 
https://github.com/Mollom/guide/blob/master/examples/php52/index.php#L344

Which is the same as a the simple approach here:
http://fideloper.com/laravel-4-trusted-proxies

There is also a good discussion about using Symfony's Request::ip method here:
http://forumsarchive.laravel.io/viewtopic.php?pid=18123
http://api.symfony.com/2.0/Symfony/Component/HttpFoundation/Request.html#method_getClientIp

**Comment by sirsquall** [comment]
Thanks for your review, it's fixed : commit 100372a
